-- Criar função para registrar acesso à vitrine
CREATE OR REPLACE FUNCTION registrar_acesso_vitrine(
  p_vitrine_id uuid,
  p_ip text,
  p_dispositivo text DEFAULT 'desktop',
  p_fonte text DEFAULT 'direto'
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO vitrine_acessos (vitrine_id, ip_hash, dispositivo, fonte, created_at)
  VALUES (p_vitrine_id, p_ip, p_dispositivo, p_fonte, now())
  ON CONFLICT DO NOTHING;

  UPDATE vitrine
  SET acessos = COALESCE(acessos, 0) + 1
  WHERE id = p_vitrine_id;
END;
$$;

-- Tabela para registrar acessos individuais (para analytics)
CREATE TABLE IF NOT EXISTS vitrine_acessos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vitrine_id uuid NOT NULL REFERENCES vitrine(id) ON DELETE CASCADE,
  ip_hash text NOT NULL,
  dispositivo text DEFAULT 'desktop',
  fonte text DEFAULT 'direto',
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vitrine_acessos_vitrine_id ON vitrine_acessos(vitrine_id);
CREATE INDEX IF NOT EXISTS idx_vitrine_acessos_created_at ON vitrine_acessos(created_at);