-- Arquivo unico para alinhar o Supabase com o frontend atual.
-- Pode ser executado no SQL Editor do Supabase.

DO $$
DECLARE
  vitrine_id_type text;
BEGIN
  SELECT pg_catalog.format_type(a.atttypid, a.atttypmod)
  INTO vitrine_id_type
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'vitrine'
    AND a.attname = 'id'
    AND a.attnum > 0
    AND NOT a.attisdropped;

  IF vitrine_id_type IS NULL THEN
    RAISE EXCEPTION 'Tabela public.vitrine ou coluna id nao encontrada';
  END IF;

  EXECUTE format($sql$
    CREATE TABLE IF NOT EXISTS public.vitrine_variacoes (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      vitrine_id %s NOT NULL REFERENCES public.vitrine(id) ON DELETE CASCADE,
      nome text NOT NULL,
      tipo_variacao text NOT NULL,
      ordem integer NOT NULL DEFAULT 0,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now()
    )
  $sql$, vitrine_id_type);
END $$;

CREATE TABLE IF NOT EXISTS public.vitrine_precos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variacao_id bigint NOT NULL REFERENCES public.vitrine_variacoes(id) ON DELETE CASCADE,
  preco numeric(10,2) NOT NULL,
  ordem integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.vitrine_precos_faixas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variacao_id bigint NOT NULL REFERENCES public.vitrine_variacoes(id) ON DELETE CASCADE,
  quantidade_minima integer NOT NULL,
  quantidade_label text NOT NULL,
  preco numeric(10,2) NOT NULL,
  destaque boolean NOT NULL DEFAULT false,
  ordem integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS vitrine_variacoes_vitrine_nome_uidx
  ON public.vitrine_variacoes (vitrine_id, nome);

CREATE INDEX IF NOT EXISTS vitrine_variacoes_vitrine_ordem_idx
  ON public.vitrine_variacoes (vitrine_id, ordem);

CREATE UNIQUE INDEX IF NOT EXISTS vitrine_precos_variacao_ordem_uidx
  ON public.vitrine_precos (variacao_id, ordem);

CREATE UNIQUE INDEX IF NOT EXISTS vitrine_precos_faixas_variacao_qtd_uidx
  ON public.vitrine_precos_faixas (variacao_id, quantidade_minima);

CREATE INDEX IF NOT EXISTS vitrine_precos_faixas_variacao_ordem_idx
  ON public.vitrine_precos_faixas (variacao_id, ordem);

-- Garante as variacoes base por tipo.
INSERT INTO public.vitrine_variacoes (vitrine_id, nome, tipo_variacao, ordem)
SELECT v.id, variacao.nome, variacao.tipo_variacao, variacao.ordem
FROM public.vitrine v
JOIN (
  VALUES
    ('canecas', 'Branca', 'cor', 1),
    ('canecas', 'Alça e Interior Preta', 'cor', 2),
    ('canecas', 'Alça e Interior Amarela', 'cor', 3),
    ('canecas', 'Alça e Interior Vermelha', 'cor', 4),
    ('canecas', 'Alça e Interior Lilás', 'cor', 5),
    ('canecas', 'Alça e Interior Azul', 'cor', 6),
    ('canecas', 'Alça e Interior Verde', 'cor', 7),
    ('xicaras', 'Com pires', 'modelo', 1),
    ('xicaras', 'Sem pires', 'modelo', 2),
    ('azulejos', '15x15', 'tamanho', 1),
    ('azulejos', '20x20', 'tamanho', 2),
    ('bottons', '33mm', 'tamanho', 1),
    ('bottons', '44mm', 'tamanho', 2),
    ('bottons', '58mm', 'tamanho', 3),
    ('canecas3d', 'Cerâmica', 'modelo', 1)
) AS variacao(tipo, nome, tipo_variacao, ordem)
  ON variacao.tipo = v.tipo
WHERE NOT EXISTS (
  SELECT 1
  FROM public.vitrine_variacoes vv
  WHERE vv.vitrine_id = v.id
    AND vv.nome = variacao.nome
);

-- Renomeia labels antigos das canecas para os labels finais com acento.
-- Quando o nome final ja existir para a mesma vitrine, remove o alias antigo
-- antes do rename para evitar colisao na unique constraint.
DELETE FROM public.vitrine_variacoes vv_antiga
USING public.vitrine v,
(
  VALUES
    ('Alca Amarela', 'Alça e Interior Amarela'),
    ('Alça Amarela', 'Alça e Interior Amarela'),
    ('Alca e Interior Amarela', 'Alça e Interior Amarela'),
    ('Alca Preta', 'Alça e Interior Preta'),
    ('Alça Preta', 'Alça e Interior Preta'),
    ('Alca e Interior Preta', 'Alça e Interior Preta'),
    ('Alca Vermelha', 'Alça e Interior Vermelha'),
    ('Alça Vermelha', 'Alça e Interior Vermelha'),
    ('Alca e Interior Vermelha', 'Alça e Interior Vermelha'),
    ('Alca Lilas', 'Alça e Interior Lilás'),
    ('Alça Lilas', 'Alça e Interior Lilás'),
    ('Alça Lilás', 'Alça e Interior Lilás'),
    ('Alca e Interior Lilas', 'Alça e Interior Lilás'),
    ('Alca Azul', 'Alça e Interior Azul'),
    ('Alça Azul', 'Alça e Interior Azul'),
    ('Alca e Interior Azul', 'Alça e Interior Azul'),
    ('Alca Verde', 'Alça e Interior Verde'),
    ('Alça Verde', 'Alça e Interior Verde'),
    ('Alca e Interior Verde', 'Alça e Interior Verde')
) AS updates(nome_atual, novo_nome),
public.vitrine_variacoes vv_final
WHERE vv_antiga.vitrine_id = v.id
  AND vv_final.vitrine_id = vv_antiga.vitrine_id
  AND vv_antiga.id <> vv_final.id
  AND vv_antiga.nome = updates.nome_atual
  AND vv_final.nome = updates.novo_nome
  AND v.tipo = 'canecas';

UPDATE public.vitrine_variacoes vv
SET nome = updates.novo_nome
FROM public.vitrine v,
(
  VALUES
    ('Alca Amarela', 'Alça e Interior Amarela'),
    ('Alça Amarela', 'Alça e Interior Amarela'),
    ('Alca e Interior Amarela', 'Alça e Interior Amarela'),
    ('Alca Preta', 'Alça e Interior Preta'),
    ('Alça Preta', 'Alça e Interior Preta'),
    ('Alca e Interior Preta', 'Alça e Interior Preta'),
    ('Alca Vermelha', 'Alça e Interior Vermelha'),
    ('Alça Vermelha', 'Alça e Interior Vermelha'),
    ('Alca e Interior Vermelha', 'Alça e Interior Vermelha'),
    ('Alca Lilas', 'Alça e Interior Lilás'),
    ('Alça Lilas', 'Alça e Interior Lilás'),
    ('Alça Lilás', 'Alça e Interior Lilás'),
    ('Alca e Interior Lilas', 'Alça e Interior Lilás'),
    ('Alca Azul', 'Alça e Interior Azul'),
    ('Alça Azul', 'Alça e Interior Azul'),
    ('Alca e Interior Azul', 'Alça e Interior Azul'),
    ('Alca Verde', 'Alça e Interior Verde'),
    ('Alça Verde', 'Alça e Interior Verde'),
    ('Alca e Interior Verde', 'Alça e Interior Verde')
) AS updates(nome_atual, novo_nome)
WHERE vv.vitrine_id = v.id
  AND updates.nome_atual = vv.nome
  AND v.tipo = 'canecas';

-- Precos fixos para canecas, xicaras, azulejos e canecas 3D.
DELETE FROM public.vitrine_precos vp
USING public.vitrine_variacoes vv, public.vitrine v
WHERE vp.variacao_id = vv.id
  AND vv.vitrine_id = v.id
  AND v.tipo IN ('canecas', 'xicaras', 'azulejos', 'canecas3d');

INSERT INTO public.vitrine_precos (variacao_id, preco, ordem)
SELECT vv.id, preco.preco, 1
FROM public.vitrine_variacoes vv
JOIN public.vitrine v ON v.id = vv.vitrine_id
JOIN (
  VALUES
    ('canecas', 'Branca', 34.90),
    ('canecas', 'Alça e Interior Preta', 46.90),
    ('canecas', 'Alça e Interior Amarela', 46.90),
    ('canecas', 'Alça e Interior Vermelha', 46.90),
    ('canecas', 'Alça e Interior Lilás', 46.90),
    ('canecas', 'Alça e Interior Azul', 46.90),
    ('canecas', 'Alça e Interior Verde', 46.90),
    ('xicaras', 'Com pires', 46.90),
    ('xicaras', 'Sem pires', 42.90),
    ('azulejos', '15x15', 29.90),
    ('azulejos', '20x20', 34.90),
    ('canecas3d', 'Cerâmica', 69.90)
) AS preco(tipo, nome, preco)
  ON preco.tipo = v.tipo
 AND preco.nome = vv.nome
WHERE NOT EXISTS (
  SELECT 1
  FROM public.vitrine_precos vp
  WHERE vp.variacao_id = vv.id
    AND vp.ordem = 1
);

-- BOTTONS personalizados: mantem a tabela de quantidades apenas para ENVIE SUA ARTE.
DELETE FROM public.vitrine_precos_faixas vpf
USING public.vitrine_variacoes vv, public.vitrine v
WHERE vpf.variacao_id = vv.id
  AND vv.vitrine_id = v.id
  AND v.tipo = 'bottons';

DELETE FROM public.vitrine_precos vp
USING public.vitrine_variacoes vv, public.vitrine v
WHERE vp.variacao_id = vv.id
  AND vv.vitrine_id = v.id
  AND v.tipo = 'bottons';

INSERT INTO public.vitrine_precos_faixas (
  variacao_id,
  quantidade_minima,
  quantidade_label,
  preco,
  destaque,
  ordem
)
SELECT vv.id, faixa.quantidade_minima, faixa.quantidade_label, faixa.preco, faixa.destaque, faixa.ordem
FROM public.vitrine_variacoes vv
JOIN public.vitrine v ON v.id = vv.vitrine_id
JOIN (
  VALUES
    ('33mm', 1, '01 a 09 un.', 4.00, false, 1),
    ('33mm', 10, '10 a 29 un.', 3.50, false, 2),
    ('33mm', 30, '30 a 49 un.', 3.00, false, 3),
    ('33mm', 50, '50 a 99 un.', 2.50, false, 4),
    ('33mm', 100, '100+ un.*', 2.30, true, 5),
    ('44mm', 1, '01 a 09 un.', 5.00, false, 1),
    ('44mm', 10, '10 a 29 un.', 4.50, false, 2),
    ('44mm', 30, '30 a 49 un.', 4.00, false, 3),
    ('44mm', 50, '50 a 99 un.', 3.50, false, 4),
    ('44mm', 100, '100+ un.*', 2.70, true, 5),
    ('58mm', 1, '01 a 09 un.', 6.00, false, 1),
    ('58mm', 10, '10 a 29 un.', 5.50, false, 2),
    ('58mm', 30, '30 a 49 un.', 5.00, false, 3),
    ('58mm', 50, '50 a 99 un.', 4.50, false, 4),
    ('58mm', 100, '100+ un.*', 3.20, true, 5)
) AS faixa(nome, quantidade_minima, quantidade_label, preco, destaque, ordem)
  ON faixa.nome = vv.nome
WHERE v.tipo = 'bottons'
  AND v.name ILIKE '%ENVIE SUA ARTE%';

-- BOTTONS prontos (kits): valor fixo por tamanho, sem tabela.
INSERT INTO public.vitrine_precos (variacao_id, preco, ordem)
SELECT vv.id, preco.preco, 1
FROM public.vitrine_variacoes vv
JOIN public.vitrine v ON v.id = vv.vitrine_id
JOIN (
  VALUES
    ('33mm', 10.00),
    ('44mm', 12.00),
    ('58mm', 15.00)
) AS preco(nome, preco)
  ON preco.nome = vv.nome
WHERE v.tipo = 'bottons'
  AND v.name ILIKE 'KIT 3%';

-- Mantem a RPC usada pelo frontend atual.
CREATE OR REPLACE FUNCTION public.increment_acessos(id_produto text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.vitrine
  SET acessos = COALESCE(acessos, 0) + 1
  WHERE id::text = id_produto;
END;
$$;
